### ISSUE TITLE
Tagging not working

### ISSUE THREAD

**Issue by guglielmo** [openpolis/open_municipio#130]
Tagging an act with a set of tags and a category result in an error:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/guglielmo/.virtualenvs/open_municipio/lib/python2.6/site-packages/taggit/utils.py", line 125, in inner
    return func(self, *args, **kwargs)
  File "/Users/guglielmo/Workspace/open_municipio/open_municipio/taxonomy/managers.py", line 30, in add
    super(_TopicableManager, self).add(*tags, **extra_kwargs)
  File "/Users/guglielmo/.virtualenvs/open_municipio/lib/python2.6/site-packages/taggit/utils.py", line 125, in inner
    return func(self, *args, **kwargs)
TypeError: add() got an unexpected keyword argument 'category'
```

This happens both on the frontend interface, with the `editor` account, and when adding tags in the random acts generator script.

To replicate, load fixtures test data, then in `shell_plus`:

```
t = Tag.objects.all()[3:5]
c = Category.objects.all()[0]
a = Act.objects.all()[0]
a.tag_set.add(*t, category=c)
```

**Comment by joke2k** [comment]
Functionality to accept keyword argument has been implemented by Lorenzo in the fork of django-taggit ([managers.py](https://github.com/seldon/django-taggit/blob/master/taggit/managers.py#L179)).

try to upgrade it.
