### ISSUE TITLE
Errore nel rebuild index con nuova versione Haystack

### ISSUE THREAD

**Issue by scaloni** [openpolis/open_municipio#537]
Acccade se si usa commit del 14 settembre o successivo.
https://github.com/toastdriven/django-haystack/commits/master

Il problema non si presenta con commit precedenti (es. https://github.com/toastdriven/django-haystack/commit/a01dc53adf8ddda4f99ae4437ad93015cf08695d)

```
(venv)om@vps36880:~/senigallia.openmunicipio.it$ django-admin.py rebuild_index --verbosity=2 --noinput
Removing all documents from your index because you said so.
All documents removed.
Traceback (most recent call last):
  File "/home/open_municipio/senigallia.openmunicipio.it/private/venv/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/home/open_municipio/senigallia.openmunicipio.it/private/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/open_municipio/senigallia.openmunicipio.it/private/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/open_municipio/senigallia.openmunicipio.it/private/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/open_municipio/senigallia.openmunicipio.it/private/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/open_municipio/senigallia.openmunicipio.it/private/venv/local/lib/python2.7/site-packages/haystack/management/commands/rebuild_index.py", line 16, in handle
    call_command('update_index', **options)
  File "/home/open_municipio/senigallia.openmunicipio.it/private/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 150, in call_command
    return klass.execute(*args, **defaults)
  File "/home/open_municipio/senigallia.openmunicipio.it/private/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/open_municipio/senigallia.openmunicipio.it/private/venv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 182, in handle
    items = load_apps()
  File "/home/open_municipio/senigallia.openmunicipio.it/private/venv/local/lib/python2.7/site-packages/haystack/utils/app_loading.py", line 51, in load_apps
    loaded_app = get_app(app_label)
  File "/home/open_municipio/senigallia.openmunicipio.it/private/venv/local/lib/python2.7/site-packages/django/db/models/loading.py", line 149, in get_app
    raise ImproperlyConfigured("App with label %s is missing a models.py module." % app_label)
django.core.exceptions.ImproperlyConfigured: App with label profiles is missing a models.py module.
```

**Comment by scaloni** [comment]
Problema evitato (provvisoriamente e solo per om-senigallia) modificando i requirements.txt
https://github.com/openmunicipio/om-senigallia/commit/7c4f647543fd3018ffe64899812765a75807fb36

**Comment by fspegni** [comment]
in generale: ove possibile dovremmo evitare requirements che scarichino
codice da git, nel qual caso il requirement dovrebbe specificare il numero
di versione da prendere

Francesco

---

"Ama le nuvole, le macchine, i libri, ma prima di tutto ama l'uomo" - Nazim
Hilkmet

http://www.manuefra.eu
skype: francesco.spegni

**Comment by fspegni** [comment]
dal messaggio sembra che ci sia una incompatibilita' fra la nuova versione di haystack e `django-profiles` che scarichiamo da qui: https://bitbucket.org/ubernostrum/django-profiles . In effetti all'applicazione `profiles` manca un file `models.py` e questo genera l'errore da parte di haystack.
